spring:
  application:
    name: Chat-Sphere-Backend

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  datasource:

    url: jdbc:postgresql://chat-sphere.c3eku6gcs1gb.us-east-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: Khadhar1210
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      minimum-idle: 2
      idle-timeout: 10000

fileNames:
  verificationCode: verification_code

mailjet:
  apiKey: 3fa1e45897449126cbe6b9afe4649e29
  apiSecretKey: 979dedb990c163e00f38f1be3f6ade02
  senderEmail: mohamedamin204080@gmail.com
  senderName: Chat Sphere Team

redis:
  redisHost: included-lion-53337.upstash.io
  redisPassword: AdBZAAIjcDFiODIyZjkzYzBmMmU0OTdjYTAzZjRmYjQ0MjBlYTUwOHAxMA

logging:
  level:
    java:
      net: debug

server:
  address: 0.0.0.0
  port: 8080

